### PR TITLE
Add microseconds to logging

### PR DESCRIPTION
**Pull request by ChefAustin**
This PR, if merged, will make Gorilla's logging timestamps include microseconds.

### CODE REVIEW

**Comment by ChefAustin** [comment]
Is the build failure something I should concern myself with? Seems to be the same failure that occured on PR #89 .

**Comment by 1dustindavis** [comment]
The build failure is cause appveyor sucks. Feel free to ignore for now.
I plan on replacing it with Github actions in the near future.

**Comment by 1dustindavis** [comment]
@ChefAustin Did you run `go test ./...` locally? I would expect this to cause a bunch of tests to fail since there is some validation that we actually log the date and time.

**Comment by ChefAustin** [comment]
You're right; I totally biffed on that one.

I'll run `go test ./...` and see if I can fix the generated errors.

**Comment by natewalck** [comment]
If you fix the output to match microseconds, the test will never pass because of the micro seconds:

```
--- FAIL: TestDebug (0.00s)
    gorillalog_test.go:70: -----
        have DEBUG: 2020/07/02 18:42:10.506547 Debug String!
        want DEBUG: 2020/07/02 18:42:10.726426 Debug String!
        -----
```

Instead of matching an exact string, I think it should use a regex instead to match the format rather than the output (Since the format is what we *really* care about here).

**Comment by natewalck** [comment]
I'd like to propose that we delete the tests in gorillalog that test the log output. We know that the log package itself has tests for the output to be consistent, so I don't think we need to test the actual output here.

This would be getting rid of `TestInfo`, `TestWarn` and `TestError`. I think the other tests are useful in that they make sure the given output is only populated when running in the desired mode.

**Comment by 1dustindavis** [comment]
Yeah, I think removing those tests seems fine.

**Comment by ChefAustin** [comment]
Rebased (in fedd2bb), removed [what I believe to be] the pesky tests (in 4b8554b) and the tests' dependency imports (in 31767f3) _but_ I fear I might've ripped-out more than I should have.

That said, definitely worth getting a second set of eyes on this diff to confirm I didn't just proverbially throw the baby out with the bathwater. 😬

Thanks for re-igniting the discussion on this change, @natewalck; I had nearly forgot about it!

**Pull request merged**
