### PR TITLE
Fix github actions & Use sys/windows to check for admin instead of powershell

### PR DESCRIPTION
**Pull request by discentem**

### CODE REVIEW

**Comment by oktN** [comment]
Please be aware that admin check should be skipped in **checkonly** mode! Thanks!

**Comment by discentem** [comment]
> Please be aware that admin check should be skipped in **checkonly** mode! Thanks!
Fixed! Good catch.

**Comment by discentem** [comment]
We shouldn't merge yet, checkonly is still broken.

**Comment by 1dustindavis** [comment]
Thanks @discentem!
_(It only took me 2 months to merge 😞)_

**Pull request merged**
